export const quoteContent = {
  slaStatement:
    "Most quotes go out within hours — no minimum order, from single prototypes to 1,000+ unit runs.",
  materials: [
    "Titanium Grade 5",
    "Inconel 625",
    "Inconel 718",
    "Stainless Steel 303",
    "Aluminum 6061-T6",
    "Aluminum 7075",
    "Aluminum 2024",
    "Copper C110",
    "PEEK",
    "Delrin",
    "PTFE",
    "UHMW PE",
    "Polycarbonate",
    "Other (specify in notes)",
  ],
  timelines: ["Standard", "Rush / expedited", "Flexible — no rush"],
  certRequirements: [
    "None required",
    "Material certification (mill cert)",
    "CMM inspection report",
    "First Article Inspection (FAI)",
    "Other (specify in notes)",
  ],
  acceptedFileExtensions: [
    ".step",
    ".stp",
    ".iges",
    ".igs",
    ".x_t",
    ".x_b",
    ".stl",
    ".pdf",
    ".dwg",
    ".dxf",
  ],
  acceptedFileLabel: "STEP, IGES, Parasolid, STL, PDF, DWG, DXF",
  maxFileSizeLabel: "45MB",
};
